### ISSUE TITLE
IndexError: list index out of range  at line 282

### ISSUE THREAD

**Issue by ghost** [sak042/Wessim#1]
<pre>
Hi I'm getting the following error immediately after starting Wessim1. 

Traceback (most recent call last):
  File "__sub_wessim1.py", line 825, in <module>
    main(sys.argv[1:])
  File "__sub_wessim1.py", line 177, in main
    gcVector = getFragmentUniform(abdlist, seqlist, last, isize, 1000, bind)
  File "__sub_wessim1.py", line 282, in getFragmentUniform
    seq = seqlist[ind][1]
IndexError: list index out of range

My command line is:

python Wessim1.py -R hg19.fa -B refseq_genes.bed -n 400000000 -o se30  -M ill100v5_s.gzip -l 50

I added some print statements and got these values right before the error happened.

('len(ABDllist): ', 47220)
('ind', '47220')
('pos', '0')
('len(seqlist)', 47220)

Adding 
if ind == len(seqlist):   
       ind -= 1
right before "seq = seqlist[ind][1]"  in getFragmentUniform(..) in __sub_wessim1.py (line 276)  
prevents the error, but wessim then continues to run indefinitely without generating any output - 
even though I set the 'number of reads' arg to 100. 
</pre>

**Comment by abolia** [comment]
Hi, 
I am getting same error running Wessim1.py 

Traceback (most recent call last):
  File "__sub_wessim1.py", line 818, in <module>
    main(sys.argv[1:])
  File "__sub_wessim1.py", line 177, in main
    gcVector = getFragmentUniform(abdlist, seqlist, last, isize, 1000, bind)
  File "__sub_wessim1.py", line 275, in getFragmentUniform
    seq = seqlist[ind][1]
IndexError: list index out of range
exiting subprocess 1

Did you have any luck figuring this out?  Please let me know if you do?

**Comment by s057** [comment]
Do you use matching identifiers for the chromosomes in bed file and fasta file? (chr1 vs 1)

**Comment by mdcao** [comment]
Hi there,
Has any one got any luck go around this problem. I have the same problem with Wessim2.py

python Wessim2.py -R ref.fasta -P probes.fasta -B probes.fasta.psl -n 1000000 -l 100 -M ../models/ill100v4_p.gzip  -pz -o result

The error message is:

Traceback (most recent call last):
  File "__sub_wessim2.py", line 899, in <module>
    main(sys.argv[1:])
  File "__sub_wessim2.py", line 239, in main
    gcVector = getFragmentUniform(fref, matchkeys, matchdic, isize, 1000, bind)
  File "__sub_wessim2.py", line 355, in getFragmentUniform
    key = pickonekey(matchkeys)
  File "__sub_wessim2.py", line 320, in pickonekey
    key = matchkeys[r]
IndexError: list index out of range
exiting subprocess 1
