### ISSUE TITLE
Reading the model zip file fails

### ISSUE THREAD

**Issue by stolpeo** [sak042/Wessim#2]
Hello,

I get an error when he reads the model zip file. For some reason he thinks that the returned data structure is a numpy ndarray, but in the code it is handled as dictionary. How can I get around this?

```
Traceback (most recent call last):
  File "/home/ocs/Software/Wessim/Wessim_ver_1.0/__sub_wessim1.py", line 818, in <module>
    main(sys.argv[1:])
  File "/home/ocs/Software/Wessim/Wessim_ver_1.0/__sub_wessim1.py", line 134, in main
    insDict=mkInserts(mx1,insD1)
  File "/home/ocs/Software/Wessim/Wessim_ver_1.0/__sub_wessim1.py", line 421, in mkInserts
    posKeys=insD.keys()
AttributeError: 'numpy.ndarray' object has no attribute 'keys'
```

Thanks,
  Oliver

**Comment by jcausey-astate** [comment]
I am observing the same error -- did you find a workaround for this?
Edited to add:
Mine was a simple oversight -- I was generating paired reads, but omitted the `-p` command line option.  Seems likely the OP has the same oversight.
